<a href="https://colab.research.google.com/github/Alexandre77777/data_mining/blob/main/1.%20%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0/1.%20%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [4]:
import numpy as np
np.version.version

'1.25.2'

2) Создать нулевой вектор размера 10

In [12]:
(f'вектор = {np.zeros(10)}' , f'размерность={np.zeros(10).shape}')

('вектор = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]', 'размерность=(10,)')

3) Создать вектор заполненный 7-ами размера 7

In [13]:
(f'вектор = {np.full(7, 7)}' , f'размерность={np.full(7, 7).shape}')

('вектор = [7 7 7 7 7 7 7]', 'размерность=(7,)')

4) Создать вектор заполненный четными числами от 10 до 100

In [16]:
(f'вектор = {np.arange(10, 101, 2)}' , f'размерность={np.arange(10, 101, 2).shape}')

('вектор = [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44\n  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80\n  82  84  86  88  90  92  94  96  98 100]',
 'размерность=(46,)')

5) Создать массив случайных чисел и развернуть его задом наперёд

In [22]:
np.random.seed(42) # пропишем seed для воспроизведения результатов

random_array = np.random.randint(1, 777, 15)  # Создаем массив из 15 случайных чисел от 1 до 777

print("Исходный массив:")
print(random_array)

reversed_array = np.flip(random_array)

print("\nМассив задом наперёд:")
print(reversed_array)


Исходный массив:
[103 436 271 107  72 701  21 615 122 467 215 331 459  88 373]

Массив задом наперёд:
[373  88 459 331 215 467 122 615  21 701  72 107 271 436 103]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [28]:
np.random.seed(34)

np.random.randint(0, 10, size=(3, 3))

array([[1, 9, 6],
       [5, 4, 3],
       [5, 2, 9]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [54]:
matrix_1 = np.zeros((4, 4))
np.fill_diagonal(matrix_1[:-1, 1:], 1) # способ первый и не очевидный

matrix = np.zeros((4, 4)) # способ второй колхозный
for i in range(3):
    matrix[i, i + 1] = 1
    

matrix_2 = np.eye(4, k=1)  # способ третий для хитрецов 


print(f'способ 1 :\n {matrix_1}')
print(f'способ 2 :\n {matrix}')
print(f'способ 3 :\n {matrix_2}')

способ 1 :
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
способ 2 :
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
способ 3 :
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [58]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чиcлами от 0 до 4 в строках.

In [59]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [95]:
matrix = np.random.randint(0, 10, size=(10, 10)) #случайные целые числа от 0 до 9.
#matrix = np.random.rand(10, 10) # альтернативный путь
row_means = np.mean(matrix, axis=1, keepdims=True)


print(f'среднее по строкам= {row_means.transpose()}' , f'\n матрица_исходная =\n {matrix}', f'\n матрица - среднее =\n {matrix - row_means}')

среднее по строкам= [[4.9 5.8 5.3 5.  5.2 4.5 5.5 4.3 4.5 4.3]] 
 матрица_исходная =
 [[4 8 4 6 2 3 8 7 2 5]
 [5 0 6 9 3 3 9 8 8 7]
 [8 0 2 8 8 1 8 7 2 9]
 [7 4 3 7 7 3 5 2 6 6]
 [3 5 5 3 3 4 9 8 6 6]
 [3 4 8 3 9 0 8 4 3 3]
 [9 5 1 2 3 9 6 9 9 2]
 [5 4 8 5 4 2 1 2 4 8]
 [8 0 2 8 9 0 7 3 0 8]
 [8 1 6 4 5 5 4 2 7 1]] 
 матрица - среднее =
 [[-0.9  3.1 -0.9  1.1 -2.9 -1.9  3.1  2.1 -2.9  0.1]
 [-0.8 -5.8  0.2  3.2 -2.8 -2.8  3.2  2.2  2.2  1.2]
 [ 2.7 -5.3 -3.3  2.7  2.7 -4.3  2.7  1.7 -3.3  3.7]
 [ 2.  -1.  -2.   2.   2.  -2.   0.  -3.   1.   1. ]
 [-2.2 -0.2 -0.2 -2.2 -2.2 -1.2  3.8  2.8  0.8  0.8]
 [-1.5 -0.5  3.5 -1.5  4.5 -4.5  3.5 -0.5 -1.5 -1.5]
 [ 3.5 -0.5 -4.5 -3.5 -2.5  3.5  0.5  3.5  3.5 -3.5]
 [ 0.7 -0.3  3.7  0.7 -0.3 -2.3 -3.3 -2.3 -0.3  3.7]
 [ 3.5 -4.5 -2.5  3.5  4.5 -4.5  2.5 -1.5 -4.5  3.5]
 [ 3.7 -3.3  1.7 -0.3  0.7  0.7 -0.3 -2.3  2.7 -3.3]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [75]:
matrix = np.random.randint(0, 10, size=(10, 10)) #случайные целые числа от 0 до 9.
#matrix = np.random.rand(10, 10) # альтернативный путь
column_medians = np.median(matrix, axis=0, keepdims=True)


print(f'медиана по строкам= \n{column_medians}' , f'\n матрица_исходная =\n {matrix}', f'\n матрица - медиана =\n {matrix - column_medians}')

медиана по строкам= 
[[3.5 4.5 3.  5.  4.5 5.5 3.  5.5 4.5 6. ]] 
 матрица_исходная =
 [[3 6 0 3 8 8 8 0 8 6]
 [7 4 6 5 4 4 3 8 4 2]
 [1 3 2 5 7 6 1 8 1 6]
 [9 0 9 0 9 1 1 6 7 4]
 [1 2 0 4 4 9 3 9 2 7]
 [4 5 6 8 6 0 2 0 7 2]
 [8 0 4 9 5 9 5 4 1 7]
 [7 7 3 5 0 5 5 9 6 9]
 [2 7 0 9 3 3 1 0 3 8]
 [1 9 3 8 0 9 9 5 5 1]] 
 матрица - медиана =
 [[-0.5  1.5 -3.  -2.   3.5  2.5  5.  -5.5  3.5  0. ]
 [ 3.5 -0.5  3.   0.  -0.5 -1.5  0.   2.5 -0.5 -4. ]
 [-2.5 -1.5 -1.   0.   2.5  0.5 -2.   2.5 -3.5  0. ]
 [ 5.5 -4.5  6.  -5.   4.5 -4.5 -2.   0.5  2.5 -2. ]
 [-2.5 -2.5 -3.  -1.  -0.5  3.5  0.   3.5 -2.5  1. ]
 [ 0.5  0.5  3.   3.   1.5 -5.5 -1.  -5.5  2.5 -4. ]
 [ 4.5 -4.5  1.   4.   0.5  3.5  2.  -1.5 -3.5  1. ]
 [ 3.5  2.5  0.   0.  -4.5 -0.5  2.   3.5  1.5  3. ]
 [-1.5  2.5 -3.   4.  -1.5 -2.5 -2.  -5.5 -1.5  2. ]
 [-2.5  4.5  0.   3.  -4.5  3.5  6.  -0.5  0.5 -5. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [93]:
matrix = np.random.rand(5, 5) 

max_values = np.max(matrix, axis=1, keepdims=True)
matrix_with_max = np.hstack((matrix, max_values))

min_values = np.min(matrix, axis=1, keepdims=True)
matrix_with_max_and_min = np.hstack((matrix_with_max, min_values))
 
print(f'матрица исходная = \n {matrix},\n максимальные строки  =  {max_values.transpose()},\n минимальные строки  =  {min_values.transpose()}, \n матрица итоговая =  \n {matrix_with_max_and_min}')

матрица исходная = 
 [[0.75818688 0.04788983 0.44213784 0.49585277 0.51401933]
 [0.97001744 0.16734625 0.63425989 0.75579273 0.392221  ]
 [0.26213968 0.0672601  0.74477488 0.32857689 0.43012907]
 [0.30193587 0.33557857 0.95440584 0.66294149 0.87826205]
 [0.43539478 0.79640971 0.85516608 0.1636599  0.9548715 ]],
 максимальные строки  =  [[0.75818688 0.97001744 0.74477488 0.95440584 0.9548715 ]],
 минимальные строки  =  [[0.04788983 0.16734625 0.0672601  0.30193587 0.1636599 ]], 
 матрица итоговая =  
 [[0.75818688 0.04788983 0.44213784 0.49585277 0.51401933 0.75818688
  0.04788983]
 [0.97001744 0.16734625 0.63425989 0.75579273 0.392221   0.97001744
  0.16734625]
 [0.26213968 0.0672601  0.74477488 0.32857689 0.43012907 0.74477488
  0.0672601 ]
 [0.30193587 0.33557857 0.95440584 0.66294149 0.87826205 0.95440584
  0.30193587]
 [0.43539478 0.79640971 0.85516608 0.1636599  0.9548715  0.9548715
  0.1636599 ]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу чётого произведения.  

In [98]:
vector = np.arange(1, 52)

odd_numbers = vector[vector % 2 == 1]
even_numbers = vector[vector % 2 == 0]

odd_matrix = odd_numbers.reshape(-1, 1)
even_matrix = even_numbers.reshape(-1, 1)

result_matrix = odd_matrix.dot(even_matrix.T)

try:
    inverse_matrix = np.linalg.inv(result_matrix)
except np.linalg.LinAlgError:
    inverse_matrix = None

print("Матрица нечетных чисел:")
print(odd_matrix.transpose())

print("\nМатрица четных чисел:")
print(even_matrix.transpose())

print("\nПроизведение матриц:")
print(result_matrix)

print("\nОбратная матрица произведения (если существует):")
print(inverse_matrix) #None - матрица не существует

Матрица нечетных чисел:
[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49 51]]

Матрица четных чисел:
[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]

Произведение матриц:
[[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  5

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [100]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1  # четные строки нечетными столбцами
matrix[::2, 1::2] = 1  # нечетные строки четными столбцами

matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])